In [ ]:
!pip install h5py pyyaml
!pip install tensorflow_text
!pip install tensorflow-text --no-dependencies

In [ ]:
import tensorflow as tf
import keras
import tensorflow_hub as hub
import os
import tensorflow_text as text

In [ ]:
!pip install transformers

In [ ]:
from transformers import BertTokenizer, TFBertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')
bert_model = TFBertModel.from_pretrained("bert-base-multilingual-cased",trainable=False)


Some layers from the model checkpoint at bert-base-multilingual-cased were not used when initializing TFBertModel: ['nsp___cls', 'mlm___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-multilingual-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [ ]:
text = "काठमाडौ ।आफूलाई सामाजिक अभियान्त बताउँदैै  "
encoded_input = tokenizer.encode(text, return_tensors='tf',add_special_tokens=True,truncation=True,max_length=512, padding='max_length')
print(encoded_input)


tf.Tensor(
[[   101  11081  35247  12347  20691  78530    920    852  28863  63401
   30472  50974    851  60270  21394  55874    887  13537 111194  28462
   15552  18438  18438    102      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0      0      0      0
       0      0      0      0      0      0      0   

In [ ]:
output = bert_model(encoded_input)['pooler_output']
print(output)

tf.Tensor(
[[ 1.58177465e-01  2.57945582e-02  1.42488614e-01 -1.79113567e-01
   9.10505056e-02  2.69242287e-01  1.22673638e-01  2.50576824e-01
  -2.49257430e-01  8.84009749e-02  6.49455860e-02 -1.90862417e-01
   5.79053350e-02 -7.23269135e-02  1.13425158e-01 -1.19451337e-01
   3.03459674e-01  1.23071652e-02  1.33755103e-01 -1.20748542e-01
  -9.99976039e-01 -1.19358689e-01 -1.56275377e-01 -7.87913278e-02
  -3.18978280e-01 -6.92354739e-02 -3.07981446e-02  8.76387767e-03
   4.97329496e-02  5.75991981e-02 -4.44863327e-02 -9.99974966e-01
   1.86802462e-01  3.00218344e-01 -2.08229735e-03 -1.02718845e-01
   5.35319932e-02  4.45593521e-02  3.28961536e-02 -3.07326168e-01
  -5.34739308e-02 -3.73814628e-02  3.03346454e-03  1.16697043e-01
  -1.65684640e-01 -1.25531763e-01  2.88453735e-02  1.16329178e-01
  -1.10415176e-01  1.77240238e-01  1.51451752e-01  1.31425202e-01
   3.03537458e-01  1.35617793e-01  6.38278872e-02  3.10585462e-02
   1.78553969e-01  1.93194926e-01  1.40135124e-01  5.78974336e-02

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [ ]:
#read file
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/minor_project/news1.csv")
df.head()

Title  \
0                      मिस नेपाल २०२२काे आवेदन खुला    
1  वीर मुस्लिम विद्यार्थीले यहूदी महिलालाई हिंस्र...   
2    भीमफेदी–कुलेखानी सुरुङमार्ग ६ परामर्शदाता छनोट    
3  स्यान्डर्स अभियानले DNC बिरूद्ध मुद्दा फिर्ता ...   
4         वामपन्थी नेता विष्णुबहादुर मानन्धरको निधन    

                                         Description  label  
0  काठमाडौं वैशाख ६ गते मिस नेपाल २०२२का आवेदन खु...      0  
1  १७ वर्षीय अहमद खलिफाले घृणित ब्रुकलिन सबवे ट्र...      1  
2  प्रदेश राजधानी हेटौंडा संघीय राजधानी काठमाडौंब...      0  
3  तपाईले महिना याद बर्नी स्यान्डर्स अभियानले DNC...      1  
4  वरिष्ठ वामपन्थी नेता विष्णुबहादुर मानन्धरको नि...      0

In [ ]:
df.drop(['Title'],axis=1,inplace=True)

In [ ]:
df.head()

Description  label
0  काठमाडौं वैशाख ६ गते मिस नेपाल २०२२का आवेदन खु...      0
1  १७ वर्षीय अहमद खलिफाले घृणित ब्रुकलिन सबवे ट्र...      1
2  प्रदेश राजधानी हेटौंडा संघीय राजधानी काठमाडौंब...      0
3  तपाईले महिना याद बर्नी स्यान्डर्स अभियानले DNC...      1
4  वरिष्ठ वामपन्थी नेता विष्णुबहादुर मानन्धरको नि...      0

In [ ]:
df[:10]

Description  label
0  काठमाडौं वैशाख ६ गते मिस नेपाल २०२२का आवेदन खु...      0
1  १७ वर्षीय अहमद खलिफाले घृणित ब्रुकलिन सबवे ट्र...      1
2  प्रदेश राजधानी हेटौंडा संघीय राजधानी काठमाडौंब...      0
3  तपाईले महिना याद बर्नी स्यान्डर्स अभियानले DNC...      1
4  वरिष्ठ वामपन्थी नेता विष्णुबहादुर मानन्धरको नि...      0
5  हिलारीले ओर्लान्डोमा आतंककारी हमलाको बयानको क्...      1
6  नेकपा एमालेले भूगोलतर्फको जिल्ला अधिवशेन एकैपट...      0
7  नेपाली कला साहित्य डट प्रतिष्ठानले कला क्षेत्र...      0
8  मुगुको जिल्ला अस्पतालमा आयोजना दिने मुटु रोग स...      0
9  वाग्मती प्रदेशकी मुख्यमन्त्री अष्टलक्ष्मी शाक्...      0

In [ ]:
token = tokenizer.encode_plus(
    df['Description'].iloc[0],
    max_length=512,
    truncation=True,
    padding='max_length',
    add_special_tokens=True,
    return_tensors='tf'
)

In [ ]:
token.input_ids

<tf.Tensor: shape=(1, 512), dtype=int32, numpy=
array([[   101,  11081,  35247,  12347,  20691,  78530,  14018,    895,
         18438, 105764,  27841,    928,    867,  17203,    889,  29822,
         29953,  61248,  21897,  21897,  15399,    852,  72109,  49978,
           866,  52736,  11208,  68860,    882,    899,  12878,  20691,
         11453,    875,  18321,  73184,  69182,  11554,    898,  13718,
         13841, 105012,    885,  27373,  25561,    898,  45753,  13841,
         44989,  11453,    852,  43263,  40340,  83510,  15399,    852,
         72109,  49978,    866,  52736,  11208, 109066,  54930,  90236,
         66880,  12347,  26803,    893,  25936,  15399,    898,  13718,
         13841, 105012,  15552,  11554,  27841,  12878,    895,  18438,
        105764,  27841,    925,  22649,    889,  29822,  49119,  24072,
         18351,  35127,  65423,  12347,  11549,  75315,  11845,  20429,
           884,  12878,  30226,  21835,  52736,  28197,  54321,    852,
         72109, 

In [ ]:
import numpy as np
X_input_ids = np.zeros((len(df), 512))
X_attn_masks = np.zeros((len(df), 512))

In [ ]:
from tqdm.auto import tqdm

def generate_training_data(df, ids, masks, tokenizer):
    for i, text in tqdm(enumerate(df['Description'])):
        tokenized_text = tokenizer.encode_plus(
            text,
            max_length=512,
            truncation=True,
            padding='max_length',
            add_special_tokens=True,
            return_tensors='tf'
        )
        ids[i, :] = tokenized_text.input_ids
        masks[i, :] = tokenized_text.attention_mask
    return ids, masks

In [ ]:
X_input_ids, X_attn_masks = generate_training_data(df, X_input_ids, X_attn_masks, tokenizer)

0it [00:00, ?it/s]

In [ ]:
X_input_ids

array([[  101., 11081., 35247., ...,     0.,     0.,     0.],
       [  101., 79143., 24332., ..., 13874., 13718.,   102.],
       [  101., 21991., 62028., ...,     0.,     0.,     0.],
       ...,
       [  101.,   108., 32441., ...,     0.,     0.,     0.],
       [  101.,   875., 53809., ...,   898., 45649.,   102.],
       [  101., 11081., 35247., ...,     0.,     0.,     0.]])

In [ ]:
X_attn_masks

array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 0., 0., 0.]])

In [ ]:
labels = np.zeros((len(df), 2))
labels.shape

(19028, 2)

In [ ]:
labels[np.arange(len(df)), df['label'].values] = 1

In [ ]:
# creating a data pipeline using tensorflow dataset utility, creates batches of data for easy loading...
dataset = tf.data.Dataset.from_tensor_slices((X_input_ids, X_attn_masks, labels))
dataset.take(1) # one sample data

<TakeDataset element_spec=(TensorSpec(shape=(512,), dtype=tf.float64, name=None), TensorSpec(shape=(512,), dtype=tf.float64, name=None), TensorSpec(shape=(2,), dtype=tf.float64, name=None))>

In [ ]:
def DatasetMapFunction(input_ids, attn_masks, labels):
    return {
        'input_ids': input_ids,
        'attention_mask': attn_masks
    }, labels


In [ ]:
dataset = dataset.map(DatasetMapFunction) # converting to required format for tensorflow dataset

In [ ]:
dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(512,), dtype=tf.float64, name=None), 'attention_mask': TensorSpec(shape=(512,), dtype=tf.float64, name=None)}, TensorSpec(shape=(2,), dtype=tf.float64, name=None))>

In [ ]:
dataset = dataset.shuffle(10000).batch(32, drop_remainder=True)

In [ ]:
p = 0.8
train_size = int((len(df)/32)*p) # for each 16 batch of data we will have len(df)//16 samples, take 80% of that for train.

In [ ]:
train_dataset = dataset.take(train_size)
test_dataset = dataset.skip(train_size)

In [ ]:
len(test_dataset)

119

In [ ]:
input_ids = tf.keras.layers.Input(shape=(512,), name='input_ids', dtype='int32')
attn_masks = tf.keras.layers.Input(shape=(512,), name='attention_mask', dtype='int32')

bert_model.bert.trainable = False
bert_embds = bert_model.bert(input_ids, attention_mask=attn_masks)[1] # 0 -> activation layer (3D), 1 -> pooled output layer (2D)


#hidden layers
intermediate_layer = tf.keras.layers.Dense(512, activation='relu', name='intermediate_layer')(bert_embds)
dropout_layer = tf.keras.layers.Dropout(0.1)(intermediate_layer)

intermediate_layer2 = tf.keras.layers.Dense(256, activation='relu', name='intermediate_layer2')(dropout_layer)
dropout_layer2 = tf.keras.layers.Dropout(0.1)(intermediate_layer2)

output_layer = tf.keras.layers.Dense(2, activation='sigmoid', name='output_layer')(dropout_layer2)
model = tf.keras.Model(inputs=[input_ids, attn_masks], outputs=output_layer)
model.summary()


Model: "model_4"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 512)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 512)]        0           []                               
                                                                                                  
 bert (TFBertMainLayer)         TFBaseModelOutputWi  177853440   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 512,                                         

In [ ]:
from keras.optimizers import Adam
optimizer = Adam(learning_rate=1e-3)

METRICS = [
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=METRICS)

In [ ]:
history = model.fit(train_dataset, validation_data=test_dataset,epochs=1)

475/475 [==============================] - 849s 2s/step - loss: 0.2248 - accuracy: 0.9034 - precision: 0.9023 - recall: 0.9047 - val_loss: 0.2246 - val_accuracy: 0.9019 - val_precision: 0.9031 - val_recall: 0.9005


In [ ]:
model.save('model.h5')

In [ ]:
#checking on new data
model = tf.keras.models.load_model('model.h5')

tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

def prepare_data(input_text, tokenizer):
    token = tokenizer.encode_plus(
        input_text,
        max_length=512,
        truncation=True,
        padding='max_length',
        add_special_tokens=True,
        return_tensors='tf'
    )
    return {
        'input_ids': tf.cast(token.input_ids, tf.float64),
        'attention_mask': tf.cast(token.attention_mask, tf.float64)
    }

def make_prediction(model, processed_data, classes=['True', 'Fake']):
    probs = model.predict(processed_data)[0]
    print(f"Prediction confidence: {probs}")
    return classes[np.argmax(probs)]

In [ ]:

input_text = input('Enter Nepali news here: ')
processed_data = prepare_data(input_text, tokenizer)
result = make_prediction(model, processed_data=processed_data)
probs = model.predict(processed_data)[0]
if result=='Fake':
  print(probs[1])
else:
  print(probs[0])

print(f"Predicted result: {result}")

Enter Nepali news here: आरजु राणा भन्ने बित्तिकै नेपाली समाजले नाक खुम्च्याउने नाम भएकाे छ । गत चुनावमा काँग्रेसलाइ आरजु राणाका नाममात्रले पनि ठूलाे घाटा परेकाे थियाे । देउवाकी श्रीमतीका नाममा उनले गरेका वा गर्ने नानाथरी कृत्य सामाजिक सञ्जाल तथा समाचारहरूमा प्रकाशित भएपछि आरजुप्रति पुरूषभन्दा पनि महिलाहरू बढि बेखुशी देखिन्थे । देउवाकी श्रीमतीलाइ जिताउन किन काँग्रेसलाइ भाेट हाल्ने ? भन्ने प्रश्न मतदाता आएकै कारण पनि काँग्रेस कमजाेर देखिएकाे हाे भन्ने कुरामा अब दुइमत नहुन सक्छ ।      यसैबीच बुढानिलकण्ठस्थित देउवानिवासका घरहरु पुराना भएकाले त्यसलाइ मर्मत संभार हुने क्रम जारी हुँदा देउवा बालुवाटारबाट धुम्बराहीमा डेरा सरेका छन् । चाैतर्फि गाली र दवाबकाबीच देउवा यतिखेर पुष २२ गते हुने समिक्षा बैठकमा कसरी प्रस्तुत हुने बारे छलफलमा छन् ।      देउवालाइ सत्ताच्युत बनाउन धारिलाे भूमिका खेलेकी आरजु देउवाभने यतिखेर गगन थापाकाे बिराेधमा घाम तापेर कुरा काट्दै बसेकी छिन् । जनआस्था लेख्छ, ११ गते सोमबार दिउँसो अढाई बजेतिर आफ्ना पतिसँग बिदा माग्न आएका उनकै क्याबिनेटका २ जना महिला मन्त्रीसामु देउवापत्नी आ

In [ ]:
#Evaluating on test dataset
    #viewing the shape of test dataset
test_dataset

In [ ]:
model.evaluate(test_dataset)